class Screen:
    """スクリーンの設定"""

    WIDTH_MARGIN = 100
    HEIGHT_MARGIN = 200
    BASE_WIDTH = 800
    BASE_HEIGHT = 800
    WIDTH = BASE_WIDTH + WIDTH_MARGIN
    HEIGHT = BASE_HEIGHT + HEIGHT_MARGIN
    START_X = WIDTH_MARGIN // 2
    START_Y = HEIGHT_MARGIN // 2
    CENTER_X = WIDTH // 2
    CENTER_Y = HEIGHT // 2
